[pico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
upload_protocol = picotool

[M5stack]
platform = espressif32
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200

[ATTINY1616]
platform = atmelmegaavr@1.9.0
board = ATtiny1616
framework = arduino
build_flags =
	-DCLOCK_SOURCE=0
board_build.f_cpu = 20000000L
upload_protocol = serialupdi
upload_speed = 230400
upload_port = COM10
board_hardware.oscillator = internal

[env:mdtest]
platform = espressif32
board = esp32dev
framework = arduino
build_flags =
    -D MDTEST
[env:can_esp32]
extends = M5stack
lib_deps =
    https://github.com/sandeepmistry/arduino-CAN.git    
    SPI
    Wire
build_flags = -D CAN_ESP32
upload_port = COM14

[env:cmoscam]
extends = pico2
build_flags =
	-D CMOSCAMERA -DUSE_PICO_STDIO
lib_deps = pico-sdk
	git@github.com:arduino-libraries/MadgwickAHRS.git
	git@github.com:jarzebski/Arduino-MPU6050.git

[env:disco_b_g431b_esc1]
platform = ststm32
board = disco_b_g431b_esc1
framework = arduino

# add
monitor_speed = 115200

build_flags =
    -DHAL_OPAMP_MODULE_ENABLED -D ESC1

lib_deps=
    askuric/Simple FOC @ ^2.3.1
    SPI
    Wire 

lib_archive = false