[pico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
upload_protocol = picotool

[env:cmoscam]
extends = pico2
build_flags =
	-D CMOSCAMERA -DUSE_PICO_STDIO
lib_deps = pico-sdk
	git@github.com:arduino-libraries/MadgwickAHRS.git
	git@github.com:jarzebski/Arduino-MPU6050.git
