// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// clock_gen //
// --------- //

#define clock_gen_wrap_target 0
#define clock_gen_wrap 2
#define clock_gen_pio_version 0

static const uint16_t clock_gen_program_instructions[] = {
            //     .wrap_target
    0xe101, //  0: set    pins, 1                [1]
    0xe100, //  1: set    pins, 0                [1]
    0x0000, //  2: jmp    0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program clock_gen_program = {
    .instructions = clock_gen_program_instructions,
    .length = 3,
    .origin = -1,
    .pio_version = clock_gen_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config clock_gen_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + clock_gen_wrap_target, offset + clock_gen_wrap);
    return c;
}
#endif

