// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// led_on //
// ------ //

#define led_on_wrap_target 0
#define led_on_wrap 0
#define led_on_pio_version 0

static const uint16_t led_on_program_instructions[] = {
            //     .wrap_target
    0xe001, //  0: set    pins, 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program led_on_program = {
    .instructions = led_on_program_instructions,
    .length = 1,
    .origin = -1,
    .pio_version = led_on_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config led_on_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + led_on_wrap_target, offset + led_on_wrap);
    return c;
}
#endif

